name: Build Frontend Assets

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Download project
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install frontend packages
        run: npm install

      - name: Build CSS and JavaScript
        run: npm run build

      - name: Create assets zip
        run: |
          cd websoccer
          zip -r ../assets.zip assets

      - name: Upload assets
        uses: actions/upload-artifact@v4
        with:
          name: openwebsoccer-assets
          path: assets.zip
